config/routes.rb
Rails.application.routes.draw do
  resources :tasks, only: [:index, :show] do
    member do
      post 'not_maked'
      post 'maked'
    end
  end
  devise_for :users

  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :todos
  has_many :users, through: :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos
  has_many :tasks, through: :todos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @todos = Todo.all
    @users = User.all
    @tasks = Task.all
  end

  def maked
    @previous_todo = Todo.find_by(user_id: current_user.id, task_id: params[:id])
    if @previous_todo.present?
      @previous_todo.update(finished: true)
      redirect_to root_path, notice: 'Tarea Actualizada'
    else
      @todo = Todo.new()
      @todo.task_id = params[:id]
      @todo.user_id = current_user.id
      @todo.finished = true
      if @todo.save
        redirect_to root_path, notice: 'Tarea Actualizada'
      else
        redirect_to root_path, alert: 'Tarea no se pudo actualizar'
      end
    end
  end

  def not_maked
    @previous_todo = Todo.find_by(user_id: current_user.id, task_id: params[:id])
    if @previous_todo.present?
      @previous_todo.update(finished: false)
      redirect_to root_path, notice: 'Tarea Actualizada'
    else
      @todo = Todo.new()
      @todo.task_id = params[:id]
      @todo.user_id = current_user.id
      @todo.finished = false
      if @todo.save
        redirect_to root_path, notice: 'Tarea Actualizada'
      else
        redirect_to root_path, alert: 'Tarea no se pudo actualizar'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaRailsIi</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0/cyborg/bootstrap.min.css" rel="stylesheet" integrity="sha384-HOjmaybB3GQTM8HunY46MvK7ngm9b/eRGOWESCQ/s+Vk4omobTY5+FXqurpSFcbz" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% if notice.present? %>
      <div class="container">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="container">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <div class="container"><%= yield %></div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Tareas', root_path, class: 'navbar-brand' %>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to current_user.email, "#", class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "#{Todo.where(user_id:current_user.id, finished: true).count} tareas listas de un total de #{@tasks.count}", '#', class: 'nav-link active' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/tasks/index.html.erb
<div class="row">
  <% @tasks.each do |task| %>
    <div class="col-md-3 mt-md-5">
      <div class="card text-center" style="margin-top ;">
        <%= image_tag task.photo, class: "card-img-top" %>
        <div class="card-body">
          <h6 class="card-title"><%= task.name %></h5>
          <% if user_signed_in? %>
              
                <%= link_to 'Deshacer', not_maked_task_path(task.id), class: "btn btn-danger", method: :post %>
              
                <%= link_to 'Realizar', maked_task_path(task.id), class: "btn btn-warning", method: :post %>
              
            <% end %>
          <%= link_to 'Ver Tarea', task_path(task.id), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/show.html.erb
<h4>Detalle de <%= @task.name %></h4>

<table class="table">
  <tr>
    <th>Usuario</th>
    <th>Estado</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <% if Todo.find_by(user_id: user.id, task_id: params[:id], finished: true) %>
        <td><%= 'Realizado' %></td>
      <% else %>
        <td><%= 'Pendiente' %></td>
      <% end %>

    </tr>
  <% end %>
</table>